clf;
t=0:0.001:1;
A=5;
fc=50;
fm=5;
m=0.5;
x=A*sin(2*%pi*fm*t);
subplot(3,1,1);
xlabel('Time');
ylabel('Amplitude');
title('Modulating Signal');
plot(t,x);
y=A*sin(2*%pi*fc*t);
subplot(3,1,2);
xlabel('Time');
ylabel('Amplitude');
title('Carrier Signal');
plot(t,y);
Zfm=A*cos(2*%pi*fc*t+m*cos(2*%pi*fm*t));
subplot(3,1,3);
xlabel('Time');
ylabel('Amplitude');
title('Modulated Signal');
plot(t,Zfm);
